### ISSUE TITLE
وسيلة أو ارطتباط

### ISSUE THREAD

**Issue by Ab-Mr** [Alsarmad/altaqwaa_android#20]
في صفحة حول ليس هناك رابط يمكن الضغط عليه لمعرفة معلومات أكثر عن التطبيق، هذا مجرد أقتراح. 

صورة توضح الامر

![Screenshot_20231017-133713.jpg](https://github.com/Alsarmad/altaqwaa_android/assets/93873156/d65838d4-7dad-407e-9ace-2e65804dbb84)

**Comment by rn0x** [comment]
تم تحسين صفحة عن التطبيق
