### ISSUE TITLE
تحديد الموقع يدوى

### ISSUE THREAD

**Issue by islam2hamy** [Alsarmad/altaqwaa_android#22]
السلام عليكم

المشكلة :
البرنامج لا يحتفظ ببيانات الموقع فى حالة ادخالها بشكل يدوى

الخطوات :

1. لا تقم بالسماح بالوصول الى الموقع
2. افتح شاشة الاعدادات
3. قم بادخال خط الطول والعرض
4. اضغط حفظ

نلاحظ :
عدم احتفاظ البرنامج بخط الطول/العرض

وجزاكم الله خيرا

**Comment by rn0x** [comment]
وعليكم السلام ورحمة الله وبركاته 
تم الإصلاح وآسف على التأخير 

9bd28f413509e10613b8620cd104c3efaa0672ee
https://github.com/Alsarmad/altaqwaa_android/releases/tag/v1.2.3

**Comment by islam2hamy** [comment]
بارك الله فيك
قمت بالتحديث وبالفعل يتم الاحتفاظ بالارقام
لكن لا يظهر مواقيت الصلاة , كل المواقيت عبارة عن 00:00

**Comment by rn0x** [comment]
وفيك بارك الله 
يعمل لدي بشكل جيد !
راح اقوم بتحسينه في اقرب وقت ان شاءالله

**Comment by islam2hamy** [comment]
ان شاء الله
جرب حذف جميع بيانات التطبيق
(كانه تثبيت جديد تمام)
ثم ادخل بيانات الموقع يدوى
