### ISSUE TITLE
خطا فى مواعيد الصلاة

### ISSUE THREAD

**Issue by islam2hamy** [Alsarmad/altaqwaa_android#26]
السلام عليكم
بارك الله فيكم وجزاكم خيرا

خطوات المشكلة :

1. قم بتثيبت البرنامج كانه جديد (او حذف جميع البيانات للبرنامج المثبت)
2. لا تسمح بالوصول لصلاحية الموقع
3. قم بادخل خط الطول والعرض يدوى (الطول : 31.24967 , العرض : 30.06263 )
4. حدد طريقة الحساب على (الهيئة المصرية للمساحة)
5. ارجع لشاشة مواقيت الصلاة

نلاحظ اختلاف المواقيت عن الموجودة بالموقع (الصبح , العشاء) , الموجودة بالموقع هى الاصح

صورة للمواقيت من البرنامج :
![Screenshot_٢٠٢٤-٠١-١٢-٢٢-١٣-٣٩-٠٥٢_com rn0x altaqwaa](https://github.com/Alsarmad/altaqwaa_android/assets/7989030/74bbfc19-3a24-45ac-bd6b-2d25bd0cb02e)

صورة للمواقيت من الموقع :
![Screenshot_٢٠٢٤-٠١-١٢-٢٢-١٣-٤٨-٨٠٥_org cromite cromite](https://github.com/Alsarmad/altaqwaa_android/assets/7989030/265d9e81-7a2f-44a2-b514-1dab317becf2)

**Comment by rn0x** [comment]
وعليكم السلام ورحمة الله وبركاته 
وفيك بارك الله 
آسف على التأخير, تم تحسين طريقة حساب اوقات الصلاة e827bfc786eb223fbd328046fcea058108402b12 
حمل الإصدار 1.2.5, اذا انحلت المشكلة ارجو إخباري

**Comment by islam2hamy** [comment]
تم الحل
بارك الله فيكم
